//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public ITEM()
        {
            this.USERORDER = new HashSet<USERORDER>();
        }
    
        public int item_id { get; set; }
        public string item_name { get; set; }
        public string item_description { get; set; }
        public double item_price { get; set; }
        public string category { get; set; }
    
        public virtual CATEGORY CATEGORY1 { get; set; }
        public virtual ICollection<USERORDER> USERORDER { get; set; }
    }
}
