//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public USERS()
        {
            this.USERORDER = new HashSet<USERORDER>();
        }
    
        public int usr_id { get; set; }
        public string usr_name { get; set; }
        public string usr_password { get; set; }
        public string usr_mail { get; set; }
    
        public virtual ICollection<USERORDER> USERORDER { get; set; }
    }
}
