//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERORDER
    {
        public USERORDER()
        {
            this.ITEM = new HashSet<ITEM>();
        }
    
        public int usr_id { get; set; }
        public int order_id { get; set; }
    
        public virtual USERS USERS { get; set; }
        public virtual ICollection<ITEM> ITEM { get; set; }
    }
}
